language: c

cache:
  directories:
    - $HOME/.stack/
    - $TRAVIS_BUILD_DIR/.stack-work/

matrix:
  include:
    - env: RESOLVER=lts-2 GHCVER=7.8.4
      addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
      os: linux

    - env: RESOLVER=lts-3 GHCVER=7.10.2
      addons: {apt: {packages: [ghc-7.10.2], sources: [hvr-ghc]}}
      os: linux

    - env: RESOLVER=lts-6 GHCVER=7.10.3
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}
      os: linux

    - env: RESOLVER=nightly GHCVER=8.0.1
      addons: {apt: {packages: [ghc-8.0.1], sources: [hvr-ghc]}}
      os: linux

    - env: RESOLVER=lts-2
      os: osx

    - env: RESOLVER=lts-3
      os: osx

    - env: RESOLVER=lts-6
      os: osx

    - env: RESOLVER=nightly
      os: osx

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - mkdir -p ~/.local/bin
  - export PATH=~/.local/bin:$PATH
  - |
    if [ `uname` = "Darwin" ]
    then
      travis_retry curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin
    else
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - chmod +x ~/.local/bin/stack
  - stack setup --stack-yaml stack-$RESOLVER.yaml

install: true

script:
  - stack build --stack-yaml stack-$RESOLVER.yaml --haddock --no-haddock-deps --test
