name: language-webassembly
version: 0.0.0
synopsis: A Haskell port of the WebAssembly spec.
category: Language
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2016 Shao Cheng
license: BSD3
github: TerrorJack/language-webassembly

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 4.10
  - text
  - vector

library:
  source-dirs: src
